# 1 per fact. if using 1 set_fact with 3 facts, dir will not be updated.

- name: combining combine_vm with vm
  set_fact:
    vm: "{{ vm | combine(combine_vm, recursive=True) }}"

- name: combining combine_dir with dir
  set_fact:
    dir: "{{ dir | combine(combine_dir, recursive=True) }}"

- name: combining combine_templates with templates
  set_fact:
    templates: "{{ templates | combine(combine_templates, recursive=True) }}"
