- name: get user running as sudo
  command: logname
  register: this

- name: update ~/.ssh/config file
  become_user: "{{ this.stdout }}"
  blockinfile:
    path: ~{{ this.stdout}}/.ssh/config
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ vm.hostname }}"
    block: |2
        Host {{ vm.hostname }}
        ServerAliveInterval 30
        IdentityFile {{ "~/" ~ vm.user.ssh_IdentityFile | regex_search(".ssh/.+") }}
        Hostname {{ vm.net.ip }}
        User {{ vm.user.name }}

- name: insert an empty line before the marker line
  replace:
    path: ~{{ this.stdout}}/.ssh/config
    regexp: "(?<=.\n)# BEGIN ANSIBLE MANAGED"
    replace: "\n# BEGIN ANSIBLE MANAGED"
